// 50-person company, 4-level hierarchy
// Level 1: Directors (3)
// Level 2: Senior Managers (8) — report to Directors
// Level 3: Team Leads (14) — report to Senior Managers
// Level 4: ICs (25) — report to Team Leads

export const FAKE_TEAM_MEMBERS = [
  // ── DIRECTORS (Level 1) ──────────────────────────────────────────────
  { id: "d1", full_name: "Sarah Chen",       email: "s.chen@acme.com",        role: "Director",        department: "Engineering",   manager_id: null,  ai_tier: "Pioneer",   ai_score: 94, access_level: "Full",     tools_used: ["Claude Code","Cursor","MCPs","GPT-4","Perplexity"],        last_assessment_date: "2026-04-01" },
  { id: "d2", full_name: "Marcus Williams",  email: "m.williams@acme.com",     role: "Director",        department: "Product",       manager_id: null,  ai_tier: "Operator",  ai_score: 78, access_level: "Advanced", tools_used: ["ChatGPT","Notion AI","Perplexity","Copilot"],               last_assessment_date: "2026-03-15" },
  { id: "d3", full_name: "Priya Kapoor",     email: "p.kapoor@acme.com",       role: "Director",        department: "Data",          manager_id: null,  ai_tier: "Pioneer",   ai_score: 91, access_level: "Full",     tools_used: ["Claude Code","Cursor","MCPs","GPT-4","Gemini"],             last_assessment_date: "2026-04-10" },

  // ── SENIOR MANAGERS (Level 2) ────────────────────────────────────────
  { id: "sm1", full_name: "James Park",      email: "j.park@acme.com",         role: "Senior Manager",  department: "Engineering",   manager_id: "d1", ai_tier: "Architect", ai_score: 68, access_level: "Standard", tools_used: ["Cursor","GitHub Copilot","ChatGPT"],                        last_assessment_date: "2026-03-20" },
  { id: "sm2", full_name: "Fatima Al-Hassan",email: "f.alhassan@acme.com",     role: "Senior Manager",  department: "Engineering",   manager_id: "d1", ai_tier: "Operator",  ai_score: 81, access_level: "Advanced", tools_used: ["Claude Code","Cursor","Perplexity","GitHub Copilot"],        last_assessment_date: "2026-04-05" },
  { id: "sm3", full_name: "Tom Nguyen",      email: "t.nguyen@acme.com",       role: "Senior Manager",  department: "Product",       manager_id: "d2", ai_tier: "Builder",   ai_score: 45, access_level: "Basic",    tools_used: ["ChatGPT","Notion AI"],                                      last_assessment_date: "2026-02-28" },
  { id: "sm4", full_name: "Lena Müller",     email: "l.muller@acme.com",       role: "Senior Manager",  department: "Product",       manager_id: "d2", ai_tier: "Architect", ai_score: 65, access_level: "Standard", tools_used: ["ChatGPT","Perplexity","Figma AI"],                          last_assessment_date: "2026-03-10" },
  { id: "sm5", full_name: "David Okafor",    email: "d.okafor@acme.com",       role: "Senior Manager",  department: "Data",          manager_id: "d3", ai_tier: "Pioneer",   ai_score: 88, access_level: "Full",     tools_used: ["Claude Code","MCPs","GPT-4","Gemini","Cursor"],             last_assessment_date: "2026-04-12" },
  { id: "sm6", full_name: "Rachel Kim",      email: "r.kim@acme.com",          role: "Senior Manager",  department: "Data",          manager_id: "d3", ai_tier: "Operator",  ai_score: 76, access_level: "Advanced", tools_used: ["Perplexity","Claude","GPT-4","Jupyter AI"],                 last_assessment_date: "2026-03-25" },
  { id: "sm7", full_name: "Alex Torres",     email: "a.torres@acme.com",       role: "Senior Manager",  department: "Engineering",   manager_id: "d1", ai_tier: "Builder",   ai_score: 42, access_level: "Basic",    tools_used: ["GitHub Copilot","ChatGPT"],                                 last_assessment_date: "2026-02-14" },
  { id: "sm8", full_name: "Nina Patel",      email: "n.patel@acme.com",        role: "Senior Manager",  department: "Product",       manager_id: "d2", ai_tier: "Spark",     ai_score: 22, access_level: "None",     tools_used: [],                                                           last_assessment_date: "2026-01-30" },

  // ── TEAM LEADS (Level 3) ─────────────────────────────────────────────
  { id: "tl1",  full_name: "Chris Adebayo",   email: "c.adebayo@acme.com",     role: "Team Lead",       department: "Engineering",   manager_id: "sm1", ai_tier: "Architect", ai_score: 62, access_level: "Standard", tools_used: ["Cursor","GitHub Copilot","ChatGPT"],           last_assessment_date: "2026-03-18" },
  { id: "tl2",  full_name: "Mei Tanaka",       email: "m.tanaka@acme.com",      role: "Team Lead",       department: "Engineering",   manager_id: "sm1", ai_tier: "Builder",   ai_score: 48, access_level: "Basic",    tools_used: ["GitHub Copilot","ChatGPT"],                    last_assessment_date: "2026-02-20" },
  { id: "tl3",  full_name: "Omar Rashid",      email: "o.rashid@acme.com",      role: "Team Lead",       department: "Engineering",   manager_id: "sm2", ai_tier: "Operator",  ai_score: 79, access_level: "Advanced", tools_used: ["Claude Code","Cursor","Perplexity"],           last_assessment_date: "2026-04-03" },
  { id: "tl4",  full_name: "Sofia Reyes",      email: "s.reyes@acme.com",       role: "Team Lead",       department: "Engineering",   manager_id: "sm2", ai_tier: "Pioneer",   ai_score: 90, access_level: "Full",     tools_used: ["Claude Code","MCPs","Cursor","GPT-4"],         last_assessment_date: "2026-04-08" },
  { id: "tl5",  full_name: "Ryan O'Brien",     email: "r.obrien@acme.com",      role: "Team Lead",       department: "Engineering",   manager_id: "sm7", ai_tier: "Spark",     ai_score: 18, access_level: "None",     tools_used: [],                                             last_assessment_date: "2026-01-15" },
  { id: "tl6",  full_name: "Aisha Mensah",     email: "a.mensah@acme.com",      role: "Team Lead",       department: "Product",       manager_id: "sm3", ai_tier: "Builder",   ai_score: 38, access_level: "Basic",    tools_used: ["ChatGPT","Notion AI"],                         last_assessment_date: "2026-02-10" },
  { id: "tl7",  full_name: "Daniel Cho",       email: "d.cho@acme.com",         role: "Team Lead",       department: "Product",       manager_id: "sm4", ai_tier: "Architect", ai_score: 67, access_level: "Standard", tools_used: ["ChatGPT","Perplexity","Figma AI"],             last_assessment_date: "2026-03-12" },
  { id: "tl8",  full_name: "Isabelle Dupont",  email: "i.dupont@acme.com",      role: "Team Lead",       department: "Product",       manager_id: "sm4", ai_tier: "Operator",  ai_score: 74, access_level: "Advanced", tools_used: ["Claude","Perplexity","Figma AI","ChatGPT"],    last_assessment_date: "2026-03-28" },
  { id: "tl9",  full_name: "Kwame Asante",     email: "k.asante@acme.com",      role: "Team Lead",       department: "Data",          manager_id: "sm5", ai_tier: "Pioneer",   ai_score: 86, access_level: "Full",     tools_used: ["Claude Code","MCPs","Gemini","GPT-4"],         last_assessment_date: "2026-04-11" },
  { id: "tl10", full_name: "Laura Schmidt",    email: "l.schmidt@acme.com",     role: "Team Lead",       department: "Data",          manager_id: "sm5", ai_tier: "Architect", ai_score: 63, access_level: "Standard", tools_used: ["Jupyter AI","GPT-4","Perplexity"],             last_assessment_date: "2026-03-22" },
  { id: "tl11", full_name: "Ben Yusuf",        email: "b.yusuf@acme.com",       role: "Team Lead",       department: "Data",          manager_id: "sm6", ai_tier: "Operator",  ai_score: 77, access_level: "Advanced", tools_used: ["Claude","GPT-4","Jupyter AI"],                 last_assessment_date: "2026-03-30" },
  { id: "tl12", full_name: "Hana Kobayashi",   email: "h.kobayashi@acme.com",   role: "Team Lead",       department: "Data",          manager_id: "sm6", ai_tier: "Builder",   ai_score: 51, access_level: "Basic",    tools_used: ["ChatGPT","Perplexity"],                        last_assessment_date: "2026-02-25" },
  { id: "tl13", full_name: "Ethan Brooks",     email: "e.brooks@acme.com",      role: "Team Lead",       department: "Product",       manager_id: "sm8", ai_tier: "Spark",     ai_score: 14, access_level: "None",     tools_used: [],                                             last_assessment_date: "2026-01-20" },
  { id: "tl14", full_name: "Amara Diallo",     email: "a.diallo@acme.com",      role: "Team Lead",       department: "Engineering",   manager_id: "sm7", ai_tier: "Builder",   ai_score: 44, access_level: "Basic",    tools_used: ["GitHub Copilot"],                             last_assessment_date: "2026-02-18" },

  // ── ICs (Level 4) ────────────────────────────────────────────────────
  { id: "ic1",  full_name: "Zoe Carter",       email: "z.carter@acme.com",      role: "IC", department: "Engineering", manager_id: "tl1", ai_tier: "Builder",   ai_score: 47, access_level: "Basic",    tools_used: ["GitHub Copilot","ChatGPT"],                    last_assessment_date: "2026-03-05" },
  { id: "ic2",  full_name: "Lucas Fernandez",  email: "l.fernandez@acme.com",   role: "IC", department: "Engineering", manager_id: "tl1", ai_tier: "Spark",     ai_score: 20, access_level: "None",     tools_used: [],                                             last_assessment_date: "2026-01-25" },
  { id: "ic3",  full_name: "Nadia Volkov",     email: "n.volkov@acme.com",      role: "IC", department: "Engineering", manager_id: "tl2", ai_tier: "Architect", ai_score: 61, access_level: "Standard", tools_used: ["Cursor","ChatGPT","GitHub Copilot"],           last_assessment_date: "2026-03-15" },
  { id: "ic4",  full_name: "Jamal Edwards",    email: "j.edwards@acme.com",     role: "IC", department: "Engineering", manager_id: "tl2", ai_tier: "Builder",   ai_score: 43, access_level: "Basic",    tools_used: ["GitHub Copilot"],                             last_assessment_date: "2026-02-22" },
  { id: "ic5",  full_name: "Yuna Lee",         email: "y.lee@acme.com",         role: "IC", department: "Engineering", manager_id: "tl3", ai_tier: "Operator",  ai_score: 82, access_level: "Advanced", tools_used: ["Claude Code","Cursor","Perplexity"],           last_assessment_date: "2026-04-02" },
  { id: "ic6",  full_name: "Patrick Osei",     email: "p.osei@acme.com",        role: "IC", department: "Engineering", manager_id: "tl3", ai_tier: "Architect", ai_score: 70, access_level: "Standard", tools_used: ["Cursor","ChatGPT","Perplexity"],               last_assessment_date: "2026-03-28" },
  { id: "ic7",  full_name: "Chloe Martin",     email: "c.martin@acme.com",      role: "IC", department: "Engineering", manager_id: "tl4", ai_tier: "Pioneer",   ai_score: 93, access_level: "Full",     tools_used: ["Claude Code","MCPs","Cursor","GPT-4"],         last_assessment_date: "2026-04-09" },
  { id: "ic8",  full_name: "Arjun Singh",      email: "a.singh@acme.com",       role: "IC", department: "Engineering", manager_id: "tl4", ai_tier: "Operator",  ai_score: 75, access_level: "Advanced", tools_used: ["Cursor","Claude","Perplexity"],                last_assessment_date: "2026-03-31" },
  { id: "ic9",  full_name: "Mia Johnson",      email: "m.johnson@acme.com",     role: "IC", department: "Engineering", manager_id: "tl5", ai_tier: "Spark",     ai_score: 12, access_level: "None",     tools_used: [],                                             last_assessment_date: "2026-01-10" },
  { id: "ic10", full_name: "Diego Ramirez",    email: "d.ramirez@acme.com",     role: "IC", department: "Engineering", manager_id: "tl5", ai_tier: "Builder",   ai_score: 36, access_level: "Basic",    tools_used: ["ChatGPT"],                                    last_assessment_date: "2026-02-05" },
  { id: "ic11", full_name: "Emeka Obi",        email: "e.obi@acme.com",         role: "IC", department: "Product",    manager_id: "tl6", ai_tier: "Builder",   ai_score: 41, access_level: "Basic",    tools_used: ["ChatGPT","Notion AI"],                         last_assessment_date: "2026-02-12" },
  { id: "ic12", full_name: "Suki Park",        email: "s.park@acme.com",        role: "IC", department: "Product",    manager_id: "tl6", ai_tier: "Spark",     ai_score: 16, access_level: "None",     tools_used: [],                                             last_assessment_date: "2026-01-18" },
  { id: "ic13", full_name: "Theo Bakker",      email: "t.bakker@acme.com",      role: "IC", department: "Product",    manager_id: "tl7", ai_tier: "Architect", ai_score: 64, access_level: "Standard", tools_used: ["ChatGPT","Figma AI","Perplexity"],             last_assessment_date: "2026-03-14" },
  { id: "ic14", full_name: "Amina Nkosi",      email: "a.nkosi@acme.com",       role: "IC", department: "Product",    manager_id: "tl7", ai_tier: "Operator",  ai_score: 80, access_level: "Advanced", tools_used: ["Claude","Perplexity","ChatGPT","Figma AI"],    last_assessment_date: "2026-04-01" },
  { id: "ic15", full_name: "Viktor Petrov",    email: "v.petrov@acme.com",      role: "IC", department: "Product",    manager_id: "tl8", ai_tier: "Pioneer",   ai_score: 89, access_level: "Full",     tools_used: ["Claude Code","MCPs","Perplexity","ChatGPT"],  last_assessment_date: "2026-04-07" },
  { id: "ic16", full_name: "Grace Afolabi",    email: "g.afolabi@acme.com",     role: "IC", department: "Product",    manager_id: "tl8", ai_tier: "Builder",   ai_score: 50, access_level: "Basic",    tools_used: ["ChatGPT","Notion AI"],                         last_assessment_date: "2026-02-26" },
  { id: "ic17", full_name: "Jin-ho Shin",      email: "j.shin@acme.com",        role: "IC", department: "Data",       manager_id: "tl9", ai_tier: "Operator",  ai_score: 83, access_level: "Advanced", tools_used: ["Gemini","GPT-4","Jupyter AI"],                 last_assessment_date: "2026-04-10" },
  { id: "ic18", full_name: "Stella Osei",      email: "s.osei@acme.com",        role: "IC", department: "Data",       manager_id: "tl9", ai_tier: "Architect", ai_score: 66, access_level: "Standard", tools_used: ["GPT-4","Perplexity","Jupyter AI"],             last_assessment_date: "2026-03-20" },
  { id: "ic19", full_name: "Remy Lefebvre",    email: "r.lefebvre@acme.com",    role: "IC", department: "Data",       manager_id: "tl10", ai_tier: "Builder",  ai_score: 53, access_level: "Basic",    tools_used: ["ChatGPT","Jupyter AI"],                        last_assessment_date: "2026-03-01" },
  { id: "ic20", full_name: "Kenji Watanabe",   email: "k.watanabe@acme.com",    role: "IC", department: "Data",       manager_id: "tl10", ai_tier: "Spark",    ai_score: 23, access_level: "None",     tools_used: [],                                             last_assessment_date: "2026-01-28" },
  { id: "ic21", full_name: "Ife Adeyemi",      email: "i.adeyemi@acme.com",     role: "IC", department: "Data",       manager_id: "tl11", ai_tier: "Architect",ai_score: 69, access_level: "Standard", tools_used: ["GPT-4","Claude","Perplexity"],                 last_assessment_date: "2026-03-24" },
  { id: "ic22", full_name: "Moana Kealoha",    email: "m.kealoha@acme.com",     role: "IC", department: "Data",       manager_id: "tl11", ai_tier: "Pioneer",  ai_score: 92, access_level: "Full",     tools_used: ["Claude Code","MCPs","Gemini","GPT-4"],         last_assessment_date: "2026-04-11" },
  { id: "ic23", full_name: "Anders Holm",      email: "a.holm@acme.com",        role: "IC", department: "Data",       manager_id: "tl12", ai_tier: "Builder",  ai_score: 46, access_level: "Basic",    tools_used: ["ChatGPT","Perplexity"],                        last_assessment_date: "2026-02-24" },
  { id: "ic24", full_name: "Tina Oduya",       email: "t.oduya@acme.com",       role: "IC", department: "Data",       manager_id: "tl12", ai_tier: "Spark",    ai_score: 19, access_level: "None",     tools_used: [],                                             last_assessment_date: "2026-01-22" },
  { id: "ic25", full_name: "Sam Abara",        email: "s.abara@acme.com",       role: "IC", department: "Product",    manager_id: "tl13", ai_tier: "Spark",    ai_score: 11, access_level: "None",     tools_used: [],                                             last_assessment_date: "2026-01-14" },
];